spring:
  application:
    name: api-gateway

server:
  port: 8080

---
spring:
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8888
---

spring:
  cloud:
    gateway:
      routes:
        - id: geologist-service
          uri: http://localhost:8083
          predicates:
            - Path=/geologist/**
          filters:
            - name: CircuitBreaker
              args:
                name: geologistCircuitBreaker
                fallbackUri: forward:/fallback/geologists

        - id: study-service
          uri: http://localhost:8082
          predicates:
            - Path=/study/**
          filters:
            - name: CircuitBreaker
              args:
                name: studyCircuitBreaker
                fallbackUri: forward:/fallback/studies

        - id: sample-service
          uri: http://localhost:8081
          predicates:
            - Path=/sample/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: sampleCircuitBreaker
                fallbackUri: forward:/fallback/samples
          logging:
            level:
              org.springframework.cloud.gateway: DEBUG
              org.springframework.web: DEBUG
