server:
  port: 9090

spring:
  application:
    name: api-gateway
  cloud:
    config:
      uri: http://localhost:8888
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: geologist-service
          uri: lb://geologist-service
          predicates:
            - Path=/geologist/**
          filters:
            - name: CircuitBreaker
              args:
                name: geologistCircuitBreaker
                fallbackUri: forward:/fallback/geologists

        - id: study-service
          uri: lb://study-service
          predicates:
            - Path=/study/**
          filters:
            - name: CircuitBreaker
              args:
                name: studyCircuitBreaker
                fallbackUri: forward:/fallback/studies

        - id: sample-service
          uri: lb://sample-service
          predicates:
            - Path=/sample/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: sampleCircuitBreaker
                fallbackUri: forward:/fallback/samples

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server.HttpServer: DEBUG
